### PR TITLE
BG-11986 update btc public fees endpoint

### PR DESCRIPTION
**Pull request by dannybitgo**
https://bitgoinc.atlassian.net/browse/BG-11986
We must update the btc public fees endpoint. This new BitGoJS has that change.

Here is the corresponding change in BitGoJS that this implements:
https://github.com/BitGo/BitGoJS/pull/309

### CODE REVIEW

**Comment by marktoda** [comment]
WRW has a text copy of the SDK?? Confused

**Comment by dannybitgo** [comment]
yeah man idk why, but it does

**Comment by dannybitgo** [comment]
its actually nice because I can get changes in more quickly without having to wait for a new npm release

**Comment by marktoda** [comment]
You could do that by pointing package.json to a commit tag or hash?

Anyways, I don't think I'll be able to give you a meaningful review here

**Pull request merged**
